### ISSUE TITLE
Submitting a transaction gives amendmentBlocked

### ISSUE THREAD

**Issue by berger-michael** [WietseWind/docker-rippled#4]
Hey. When I submit a transaction I get an error message stating:       "error_message": "Amendment blocked, need upgrade.",

I am using the test net. Here are the calls I am making:
`{
    "method": "submit",
    "params": [
        {
            "offline": false,
            "secret": "shb2MeSPMjbk4bTGFWjckU2WkuwbU",
            "tx_json": {
                "Account": "rnGkgVq1d1TbSRbEKn4LYuphuHitoDsLD2",
                "Amount": "199",
                "Destination": "rGEj2VrKC1AKRXMcHkrcZcTy2Q2iL8eVSP",
                "TransactionType": "Payment"
            },
            "fee_mult_max": 1000
        }
    ]
}`

I get this response:

`{
    "result": {
        "error": "amendmentBlocked",
        "error_code": 14,
        "error_message": "Amendment blocked, need upgrade.",
        "request": {
            "command": "submit",
            "fee_mult_max": 1000,
            "offline": false,
            "secret": "<masked>",
            "tx_json": {
                "Account": "rnGkgVq1d1TbSRbEKn4LYuphuHitoDsLD2",
                "Amount": "199",
                "Destination": "rGEj2VrKC1AKRXMcHkrcZcTy2Q2iL8eVSP",
                "TransactionType": "Payment"
            }
        },
        "status": "error"
    }
}`

**Comment by WietseWind** [comment]
Are you sure you are running a recent version of rippled? If you run the server_info command, what is the version reported back to you?


P.S. your secret is exposed in the copy paste command.

--- original message ---
> Mon, 4 Mar at 5:35 PM, <notifications@github.com> wrote:


> Hey. When I submit a transaction I get an error message stating: "error_message": "Amendment blocked, need upgrade.",

> I am using the test net. Here are the calls I am making:

> { "method": "submit", "params": [ { "offline": false, "secret": "shb2MeSPMjbk4bTGFWjckU2WkuwbU", "tx_json": { "Account": "rnGkgVq1d1TbSRbEKn4LYuphuHitoDsLD2", "Amount": "199", "Destination": "rGEj2VrKC1AKRXMcHkrcZcTy2Q2iL8eVSP", "TransactionType": "Payment" }, "fee_mult_max": 1000 } ] }

> I get this response:

> { "result": { "error": "amendmentBlocked", "error_code": 14, "error_message": "Amendment blocked, need upgrade.", "request": { "command": "submit", "fee_mult_max": 1000, "offline": false, "secret": "<masked>", "tx_json": { "Account": "rnGkgVq1d1TbSRbEKn4LYuphuHitoDsLD2", "Amount": "199", "Destination": "rGEj2VrKC1AKRXMcHkrcZcTy2Q2iL8eVSP", "TransactionType": "Payment" } }, "status": "error" } }

> —

> You are receiving this because you are subscribed to this thread.

> Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by berger-michael** [comment]
Build Version 1.1.1. Thanks about the secret. But I am connected to the testnet, so  I am fine to generate a new account. Here is the full return from server_info

How should I be signing and submitting transactions? 
I can do a sign method, but I also get amendment_blocked when I try and do a submit after the sign.

`{
    "result": {
        "info": {
            "amendment_blocked": true,
            "build_version": "1.1.1",
            "complete_ledgers": "17474898-17500522",
            "hostid": "EDIT",
            "io_latency_ms": 1,
            "jq_trans_overflow": "0",
            "last_close": {
                "converge_time_s": 2,
                "proposers": 16
            },
            "load_factor": 1,
            "peer_disconnects": "355",
            "peer_disconnects_resources": "0",
            "peers": 21,
            "pubkey_node": "n9MTzvdLY3GeYoF1goHbJsac7amxTuEUYFomCoZ2E85WNpSssMHK",
            "server_state": "tracking",
            "state_accounting": {
                "connected": {
                    "duration_us": "215599352",
                    "transitions": 1
                },
                "disconnected": {
                    "duration_us": "1284735",
                    "transitions": 1
                },
                "full": {
                    "duration_us": "0",
                    "transitions": 0
                },
                "syncing": {
                    "duration_us": "82162298",
                    "transitions": 37
                },
                "tracking": {
                    "duration_us": "76729148145",
                    "transitions": 38
                }
            },
            "time": "2019-Mar-05 13:45:23.546338",
            "uptime": 77028,
            "validated_ledger": {
                "age": 2,
                "base_fee_xrp": 0.00001,
                "hash": "E4233AFA825E710AADB2F596F6E1B76721B3461BB1EEEB1515DCDD6A16CE6D91",
                "reserve_base_xrp": 20,
                "reserve_inc_xrp": 5,
                "seq": 17500522
            },
            "validation_quorum": 13
        },
        "status": "success"
    }
}`

**Comment by WietseWind** [comment]
Dat verklaart, dat is een oude versie. Je kunt de container stoppen, de container verwijderen, de image verwijderen en de container opnieuw maken zodat de meest recente image wordt gedownload van de Docker Hub.


```
docker stop {containernaam}
docker rm {containernaam}
docker rmi xrptipbot/rippled
```

--- original message ---
On March 5, 2019, 2:47 PM GMT+1 notifications@github.com wrote:


Build Version 1.1.1. Thanks about the secret. But I am connected to the testnet, so I am fine to generate a new account. Here is the full return from server_info

How should I be signing and submitting transactions?

I can do a sign method, but I also get amendment_blocked when I try and do a submit after the sign.

{ "result": { "info": { "amendment_blocked": true, "build_version": "1.1.1", "complete_ledgers": "17474898-17500522", "hostid": "EDIT", "io_latency_ms": 1, "jq_trans_overflow": "0", "last_close": { "converge_time_s": 2, "proposers": 16 }, "load_factor": 1, "peer_disconnects": "355", "peer_disconnects_resources": "0", "peers": 21, "pubkey_node": "n9MTzvdLY3GeYoF1goHbJsac7amxTuEUYFomCoZ2E85WNpSssMHK", "server_state": "tracking", "state_accounting": { "connected": { "duration_us": "215599352", "transitions": 1 }, "disconnected": { "duration_us": "1284735", "transitions": 1 }, "full": { "duration_us": "0", "transitions": 0 }, "syncing": { "duration_us": "82162298", "transitions": 37 }, "tracking": { "duration_us": "76729148145", "transitions": 38 } }, "time": "2019-Mar-05 13:45:23.546338", "uptime": 77028, "validated_ledger": { "age": 2, "base_fee_xrp": 0.00001, "hash": "E4233AFA825E710AADB2F596F6E1B76721B3461BB1EEEB1515DCDD6A16CE6D91", "reserve_base_xrp": 20, "reserve_inc_xrp": 5, "seq": 17500522 }, "validation_quorum": 13 }, "status": "success" } }

—

You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by berger-michael** [comment]
Thanks! That did it!

**Comment by WietseWind** [comment]
That's @WietseWind - https://github.com/WietseWind/

Thanks!

--

Yours,
Wietse Wind

CEO @ XRPL Labs, Xumm
The #1 XRP Ledger wallet

On February 28, 2024 at 10:58 PM, Cate Papez ***@***.***) wrote:

Hi Wietse,

Can you please share your github handle? Rohit, cc'd, will get you set up
as a maintainer in advance of Friday's maintainer's meeting. Thank you,
Cate

---------- Forwarded message ---------
From: *Cate Papez* ***@***.***>
Date: Tue, Feb 27, 2024 at 8:41 PM
Subject: Welcome, XRPL Labs!
To: Wietse (XRPL Labs) ***@***.***>, Leemon Baird <
***@***.***>, John Woods ***@***.***>, Blanca
Quiroz ***@***.***>
Cc: Zenobia Godschalk ***@***.***>


Hi Wietse, connecting you with Leemon, John, and the Swirlds Labs marketing
team. Congratulations on joining as a Founding Member.  The Alliance is
thrilled to have you on board.

A few things for you:


   - We'll set up a meeting of the Technical Oversight Committee (you,
   Leemon, John) for next week so the three of you can connect on upcoming
   priorities.
   - We'll pull you into the derecalliance slack instance this week.
   - Leemon would like to you to join, if you are free, the first
   maintainer's meeting taking place this Friday, March 1st. Invite to follow.
   - Finally, connecting you here with Zenobia as she'll be your PR point
   of contact for the announcement of the next set of members.

***@***.*** Quiroz* ***@***.***> , can you please help with
coordinating 30 mins between Leemon, John, and Wietse for next week?

Wietse, please let us know if you have any questions.
Best,Cate

-- 


Cate Papez

Chief of Staff

Phone: 978.989.2553

Email: ***@***.***

SwirldsLabs.com <https://swirldslabs.com/>


-- 


Cate Papez

Chief of Staff

Phone: 978.989.2553

Email: ***@***.***

SwirldsLabs.com <https://swirldslabs.com/>
